# Generated by Django 5.2.2 on 2025-06-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
